### ISSUE TITLE
Call to a member function cleanIntArray() on null

### ISSUE THREAD

**Issue by EvelynProjects** [franzholz/table#6]
Following error occurs: 
Call to a member function cleanIntArray() on null
in /var/www/html/public/typo3conf/ext/table/lib/class.tx_table_db.php line 1931:
` $query.=' AND ' . $this->aliasArray[$table] . '.pid IN (' . implode(',', $GLOBALS['TYPO3_DB']->cleanIntArray($listArr)) . `')';``

As far as I know $GLOBALS['TYPO3_DB'] is deprecated. 

Additional information: 
I have installed the typo3 extension tt_products (=Shop System; version 2.9.13) , which use this table exension.
I have checked the version of the table extension twice: 0.8.0
The typo3 version is 10.4.16

**Comment by franzholz** [comment]
You must install typo3db_legacy.

**Comment by EvelynProjects** [comment]
Oh, I'm sorry.
Thank you very much! Now it works :)
